It is used for fast mathematical and numerical operations. used for numerical computing and working with arrays.

used for working with numbers, arrays, and mathematical operations.

In [1]:
import numpy as np 

In [2]:
array = np.array([10,20,30,40,50,60,70,80,90])
array

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
for a,b in enumerate (array):      # enumerate() function is used to get the index and value of the array
    print(f"array[{a}] : {b}")

array[0] : 10
array[1] : 20
array[2] : 30
array[3] : 40
array[4] : 50
array[5] : 60
array[6] : 70
array[7] : 80
array[8] : 90


In [4]:
array[0] = 100
array

array([100,  20,  30,  40,  50,  60,  70,  80,  90])

In [5]:
print(array[3:6])    # slicing the array from index 3 to 5

[40 50 60]


In [6]:
array[[1,3]]=101,102
array

array([100, 101,  30, 102,  50,  60,  70,  80,  90])

In [7]:
arr =np.append(array,110)       # adding at the end of the array
print("arr:",arr,end="\n\n")

arr1 = np.insert(arr,0,100)     # adding at the beginning of the array
print("arr1:",arr1)

arr1 = np.delete(arr1,0)


arr: [100 101  30 102  50  60  70  80  90 110]

arr1: [100 100 101  30 102  50  60  70  80  90 110]


In [8]:
print("Size of arr:", arr.size)

Size of arr: 10


In [9]:
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
arr2.ndim

3

In [10]:
arr2.shape

(2, 3, 3)

In [11]:
print(arr2,end="\n\n")
print("mean:",arr2.mean())

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

mean: 5.0


In [12]:
print("standard deviation:",arr2.std())

standard deviation: 2.581988897471611


In [13]:
print("max:",arr2.max())

max: 9


In [14]:
print("min:",arr2.min())

min: 1


In [15]:
arr2 = np.pi
arr2

3.141592653589793

In [16]:
a = ([100,200,300,400])
b = ([15,16,17,18])
np.add(a,b)

array([115, 216, 317, 418])

In [17]:
np.subtract(a,b)

array([ 85, 184, 283, 382])

#Broadcasting works from right to left 

means the dimensions of the arrays should be in the same order or either be 1 

eg (2,3) and (3,2) is not valid

(2,3) and (1,3)  is valid 

if (2,3) and (3,) it read it as (1,3)

but (2,4)  and (4,4) is not valid 

In [18]:
print(arr,"\n",arr1,"\n")

print("Shape of arr:", arr.shape)
print("Shape of arr1:", arr1.shape)         


np.multiply(arr,arr1)

[100 101  30 102  50  60  70  80  90 110] 
 [100 101  30 102  50  60  70  80  90 110] 

Shape of arr: (10,)
Shape of arr1: (10,)


array([10000, 10201,   900, 10404,  2500,  3600,  4900,  6400,  8100,
       12100])

In [19]:
print(arr,"\n",arr1)
np.divide(arr,arr1)

[100 101  30 102  50  60  70  80  90 110] 
 [100 101  30 102  50  60  70  80  90 110]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

The dot product is a mathematical operation between two vectors

(1×4) + (2×5) + (3×6)
= 4 + 10 + 18
= 32

In [20]:
arr2 = np.array([1,2,3])
arr3 = np.array([40,58,67])
print(arr2,"\n",arr3)
np.dot(arr2,arr3)

[1 2 3] 
 [40 58 67]


np.int64(357)

2 rows ,3 columns ---> So shape = (2,3)   
2 rows ,3 columns ---> So shape = (2,3)   
For matrix multiplication (what np.dot does for 2D arrays):

# 👉 Columns of first matrix must equal rows of second matrix

Columns of arr4 = 3
Rows of arr5 = 2
❌ 3 ≠ 2

Columns of arr4 = 3
Rows of arr5.T = 3
✅ 3 = 3 → Now it works!

In [21]:
arr4 = np.array([[1,2,3],[4,5,6]])
arr5 = np.array([[7,8,9],[10,11,12],[13,14,15]])

print(arr4.shape,"\n",arr5.shape)
print(arr4.ndim,"\n\n",arr5.ndim)
np.dot(arr4,arr5)

(2, 3) 
 (3, 3)
2 

 2


array([[ 66,  72,  78],
       [156, 171, 186]])

In [22]:
print(arr3)
result = arr3+4
result

[40 58 67]


array([44, 62, 71])

A radian is an angle measurement unit.

# Trigonometry & Geometry Projects

project involves angles, rotations, or circles.

Drawing circles or arcs in graphics.

Calculating the position of points on a circle

# In physics, radians are standard for angular motion. 

Rotating wheels, pendulums, or planets.

In [23]:
rad1 = np.array([1,np.pi,np.pi/2,3*np.pi/2])
rad1

array([1.        , 3.14159265, 1.57079633, 4.71238898])

In [24]:
print(np.linspace(-1,1,5))

[-1.  -0.5  0.   0.5  1. ]


In [25]:
new_array = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
new_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
print(new_array.ndim)

2


In [27]:
print(new_array.shape)

(5, 2)


In [28]:
new_arr1 = np.array([[1,2],[3,4],[5,6]])
new_arr2 = np.array([[7,8],[9,10],[11,12]])
print(new_arr1,'\n',new_arr2)

[[1 2]
 [3 4]
 [5 6]] 
 [[ 7  8]
 [ 9 10]
 [11 12]]


In [29]:
np.add(new_arr1,new_arr2)

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [30]:
np.subtract(new_arr1,new_arr2)

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [31]:
np.multiply(new_arr1,new_arr2)

array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [32]:
np.divide(new_arr1,new_arr2)

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ],
       [0.45454545, 0.5       ]])

In [33]:
r = np.arange(10)
print(r)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
r.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])