In [154]:
import numpy as np 

In [155]:
array = np.array([10,20,30,40,50,60,70,80,90])
array

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [156]:
for a,b in enumerate (array):      # enumerate() function is used to get the index and value of the array
    print(f"array[{a}] : {b}")

array[0] : 10
array[1] : 20
array[2] : 30
array[3] : 40
array[4] : 50
array[5] : 60
array[6] : 70
array[7] : 80
array[8] : 90


In [157]:
array[0] = 100
array

array([100,  20,  30,  40,  50,  60,  70,  80,  90])

In [158]:
print(array[3:6])    # slicing the array from index 3 to 5

[40 50 60]


In [159]:
array[1:3] = 101,102
array

array([100, 101, 102,  40,  50,  60,  70,  80,  90])

In [160]:
arr =np.append(array,110)       # adding at the end of the array
print("arr:",arr,end="\n\n")

arr1 = np.insert(arr,0,100)     # adding at the beginning of the array
print("arr1:",arr1)

arr1 = np.delete(arr1,0)

arr: [100 101 102  40  50  60  70  80  90 110]

arr1: [100 100 101 102  40  50  60  70  80  90 110]


In [161]:
print("Size of arr:", arr.size)

Size of arr: 10


In [162]:
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
arr2.ndim

3

In [163]:
arr2.shape

(2, 3, 3)

In [164]:
print(arr2,end="\n\n")
print("mean:",arr2.mean())

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

mean: 5.0


In [165]:
print("standard deviation:",arr2.std())

standard deviation: 2.581988897471611


In [166]:
print("max:",arr2.max())

max: 9


In [167]:
print("min:",arr2.min())

min: 1


In [168]:
arr2 = np.pi
arr2

3.141592653589793

In [169]:
a = ([100,200,300,400])
b = ([15,16,17,18])
np.add(a,b)

array([115, 216, 317, 418])

In [170]:
np.subtract(a,b)

array([ 85, 184, 283, 382])

#Broadcasting works from right to left 
means the dimensions of the arrays should be in the same order 
or either be 1 
eg (2,3) and (3,2) is not valid
(2,3) and (1,3)  is valid 
if (2,3) and (3,) it read it as (1,3)
but (2,4)  and (4,4) is not valid 

In [174]:
print(arr,"\n",arr1,"\n")

print("Shape of arr:", arr.shape)
print("Shape of arr1:", arr1.shape)         


np.multiply(arr,arr1)

[100 101 102  40  50  60  70  80  90 110] 
 [100 101 102  40  50  60  70  80  90 110] 

Shape of arr: (10,)
Shape of arr1: (10,)


array([10000, 10201, 10404,  1600,  2500,  3600,  4900,  6400,  8100,
       12100])

In [175]:
print(arr,"\n",arr1)
np.divide(arr,arr1)

[100 101 102  40  50  60  70  80  90 110] 
 [100 101 102  40  50  60  70  80  90 110]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

The dot product is a mathematical operation between two vectors

(1×4) + (2×5) + (3×6)
= 4 + 10 + 18
= 32

In [177]:
arr2 = np.array([1,2,3])
arr3 = np.array([4,5,6])
print(arr2,"\n",arr3)
np.dot(arr2,arr3)

[1 2 3] 
 [4 5 6]


np.int64(32)

2 rows ,3 columns ---> So shape = (2,3)   
2 rows ,3 columns ---> So shape = (2,3)   
For matrix multiplication (what np.dot does for 2D arrays):

# 👉 Columns of first matrix must equal rows of second matrix

Columns of arr4 = 3
Rows of arr5 = 2
❌ 3 ≠ 2

Columns of arr4 = 3
Rows of arr5.T = 3
✅ 3 = 3 → Now it works!

In [191]:
arr4 = np.array([[1,2,3],[4,5,6]])
arr5 = np.array([[7,8,9],[10,11,12],[13,14,15]])

print(arr4.shape,"\n",arr5.shape)
print(arr4.ndim,"\n \n",arr5.ndim)
np.dot(arr4,arr5)

(2, 3) 
 (3, 3)
2 
 
 2


array([[ 66,  72,  78],
       [156, 171, 186]])